### ISSUE TITLE
無限DM通知問題？

### ISSUE THREAD

**Issue by kotarot** [kotarot/shi-mt-bot#2]
無限DM通知問題らしい

**Comment by kotarot** [comment]
とりあえずDMの宛先を修正した。

**Comment by kotarot** [comment]
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.3/site-packages/twitter/api.py", line 315, in _handle_response
    handle = urllib_request.urlopen(req, *_kwargs)
  File "/usr/local/python/lib/python3.3/urllib/request.py", line 160, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python/lib/python3.3/urllib/request.py", line 479, in open
    response = meth(req, response)
  File "/usr/local/python/lib/python3.3/urllib/request.py", line 591, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python/lib/python3.3/urllib/request.py", line 517, in error
    return self._call_chain(_args)
  File "/usr/local/python/lib/python3.3/urllib/request.py", line 451, in _call_chain
    result = func(*args)
  File "/usr/local/python/lib/python3.3/urllib/request.py", line 599, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "(省略)/shibot/bot/shibot.py", line 126, in <module>
    t.direct_messages.new(user=admin, text=status)
  File "/usr/local/python/lib/python3.3/site-packages/twitter/api.py", line 308, in **call**
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/local/python/lib/python3.3/site-packages/twitter/api.py", line 341, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 403 for URL: 1.1/direct_messages/new.json using parameters: (省略)
details: {'errors': [{'code': 226, 'message': "This request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later."}]}

**Comment by kotarot** [comment]
ということらしい。
DM通知機能を廃止する。

**Comment by kotarot** [comment]
ひとまず master にマージはせず保留にしておく。
